### PR TITLE
Update dependencies due to security vulnerabilities

### PR DESCRIPTION
**Pull request by gabceb**
- Bumped dependencies
- Bumped the package version to 1.0.0 to keep it safe. This package has now been running for a while with production code

### CODE REVIEW

**Review by feliun — APPROVED** [review]
LGTM, although I think `assignIn` is just an alias to `extend`

**Review by rouanw — COMMENTED** [review]
Looks good to me.

One reason you may not want to bump the major version is so that consumers will get the security improvements by default, rather than having to upgrade.

**Comment by gabceb** [comment]
I thought about that but I did bump a major of handlebars so I would rather stay on the safe side of things and not break someome using the lib

**Comment by gabceb** [comment]
2 LGTM. Anyone brave enough to actually merge it? :trollface:

**Comment by hustler** [comment]
I really need this :) I'm not brave - but merging

**Pull request merged**
